config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name="home"),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name="about"),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    url(r'^users/', include("marketing_program_v2.users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^leads/', include("marketing_program_v2.leads.urls", namespace="leads")),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception("Bad Request!")}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception("Permission Denied")}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception("Page not Found")}),
        url(r'^500/$', default_views.server_error),
    ]

marketing_program_v2/leads/urls.py
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from .views import AboutView, LeadView, FilterView

urlpatterns = (
    url(
        r'^$', AboutView.as_view(), name="home"
    ),
    url(
        r'^view/', LeadView.as_view(), name="view"
    ),
    url(
        r'^filter/', FilterView.as_view(), name="filter"
    ),
)

marketing_program_v2/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

marketing_program_v2/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_("Name of User"), blank=True, max_length=255)
    client_id = models.CharField(_("Client ID"), blank=True, max_length=255)
    client_secret = models.CharField(_("Client Secret"), blank=True, max_length=255)
    instance = models.CharField(_("Instance URL"), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

marketing_program_v2/leads/forms.py
from django import forms


class CustomForm(forms.Form):
    field_set_name = forms.CharField()

marketing_program_v2/leads/views.py
from __future__ import absolute_import, unicode_literals

import csv
import sys

from django.db import connection
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import ListView

from .models import Leads, Fields
from .tasks import get_leads

reload(sys)
sys.setdefaultencoding('utf8')


class AboutView(ListView):
    template_name = "leads/leads.html"
    context_object_name = "fields"
    model = Fields
    queryset = Fields.object.all()


# class CustomFieldForm(FormView):
#     def get(self, request):
#         # if "save_fields" in request.GET:
#         print "success"
#         return render(request, "leads/leads.html")


class LeadView(AboutView, ListView):
    template_name = "leads/view.html"
    context_object_name = "leads"
    model = Leads

    def datatype_retrieval(self, request):
        lead_num = Leads.object.all().count()  # Total number of leads in database
        ids = Leads.object.values('id')
        existing_ids = [id['id'] for id in ids]
        fields = request.POST.getlist('selectfields')  # 'fields' is a list of user-selected rest names
        fields.insert(0, "id")
        result = get_leads.delay(existing_ids, fields, request.user.client_id, request.user.client_secret, request.user.instance) # LIVE DON'T UNCOMMENT

        queryset = Leads.object.all().values('document')[:100]  # 'leads' is the Leads table.
        FieldsEntries = Fields.object.all()  # Everything from the 'Fields' database
        datatypes = []
        for field in fields:
            for entry in FieldsEntries:
                if field == entry.rest_name:
                    datatypes.append(entry.data_type)
        return lead_num, fields, queryset, datatypes

    def data_sort(self, request, fields, datatypes):
        fielddata = dict(zip(fields, datatypes))  # 'fieldata' is a dictionary with fields and associated data type
        request.session['fielddata'] = fielddata
        string, range1, boolean, dummy = 0, 0, 0, 0
        for field, datatype in fielddata.iteritems():
            if datatype in "string email phone text url":
                string += 1  # string--> string, email, phone, text, and url datatypes
            elif datatype in "currency float date datetime integer":
                range1 += 1  # range--> currency, float, date, datetime, and integer datatypes
            elif datatype == "boolean":
                boolean += 1  # boolean--> boolean datatype
            else:
                dummy += 1  # errors
        # 'fieldtype' Dictionary on what data types are included in 'fielddata'.
        fieldtype = {"string": string, "range": range1, "boolean": boolean, "dummy": dummy}
        return fieldtype, fielddata

    def table_fill(self, fielddata, queryset):
        tabledict = {'id': []}
        tablelist = ['id']
        for field, datatype in fielddata.iteritems():
            if field != "id":
                tablelist.append(field)
                tabledict.update({field: []})
        for header in tablelist:
            for lead in queryset:
                for json, document in lead.iteritems():
                    if header in document:
                        tabledict[header].append(document[header])
                    else:
                        tabledict[header].append("---")
        return tabledict, tablelist

    def post(self, request):
        if "get_leads" in request.POST:
            lead_num, fields, queryset, datatypes = self.datatype_retrieval(request)
            fieldtype, fielddata = self.data_sort(request, fields, datatypes)
            tabledict, tablelist = self.table_fill(fielddata, queryset)
            return render(request, "leads/view.html", {'leads': queryset, 'fields': fields, 'lead_num': lead_num,
                                                       'fielddata': fielddata, 'fieldtype': fieldtype,
                                                       'tablelist': tablelist, 'tabledict': tabledict})
        elif "saveSubmit" in request.POST:
            template_name = "leads/leads.html"
            return render(request, "leads/leads.html")


class FilterView(LeadView, ListView):
    template_name = "leads/filter.html"
    context_object_name = "leads"
    model = Leads
    queryset = Leads.object.all().values('document')

    def user_filters(self, request):
        fields = []
        # These 1st IF statements matches up id filter values with 'idstart' and 'idend'
        if request.POST['id_start'] == "":
            idstart = request.POST['id_start']
        else:
            idstart = int(request.POST['id_start'])
        if request.POST['id_end'] == "":
            idend = request.POST['id_end']
        else:
            idend = int(request.POST['id_end'])

        filters = {'id': [idstart, idend]}  # The creation of the 'filters' dictionary
        for key, value in request.POST.items():
            if 'selectfields' in key:  # Rest Names taken from hiiden input fields
                fields.append(value)
            elif '_start' in key and 'id' not in key:  # non-date ranges are converted to floats
                a = key[:-6]  # "start" is removed form the rest name, then value is made into key for 'filters' entry
                if value == "":
                    b = value
                else:
                    b = float(value)  # start value converted from string to float
                for key2, value2 in request.POST.items():
                    if a + '_end' in key2:
                        if value2 == "":
                            c = value2
                        else:
                            c = float(value2)  # The 'end' or max value is converted to float to be added to 'filters'
                filters.update({a: [b, c]})  # non-date and non-id range is added to 'filters'
            elif 'dstart' in key and 'id' not in key:  # date and datetime variables are NOT converted to floats
                a = key[:-6]
                b = value
                for key2, value2 in request.POST.items():
                    if a + 'dend' in key2:
                        c = value2
                filters.update({a: [b, c]})  # date type is added to 'filters'
            elif '_str' in key:
                filters.update({key[:-4]: value})
            elif '_boolean' in key:
                filters.update({key[:-8]: value})
        return filters, fields

    def object_create(self, key, object_list):
        object_part = "'" + key + "', document ->> '" + key + "'"
        object_list.append(object_part)
        return object_list

    def range_filter(self, key, value, param, querySTR, data_type, filter_clause):
        if value[0] == "" and value[1] == "":
            pass
        elif value[1] != "" and value[1] != "":
            param.append(value[0])
            param.append(value[1])
            paramSTR = "CAST(document->>'" + key + "' AS " + data_type + " ) BETWEEN %s AND %s "
            querySTR.append(paramSTR)
            filter_clause = 1
        elif value[0] != "" and value[1] == "":
            param.append(value[1])
            paramSTR = "CAST(document->>'" + key + "' AS " + data_type + " ) < %s "
            querySTR.append(paramSTR)
            filter_clause = 1
        elif value[0] == "" and value[1] != "":
            param.append(value[1])
            paramSTR = "CAST(document->>'" + key + "' AS " + data_type + " ) < %s "
            querySTR.append(paramSTR)
            filter_clause = 1
        return param, querySTR, filter_clause

    def SQL_filter(self, filters, fielddata):
        object_list, param, querySTR, querySQL = [], [], [], []
        filter_clause = 0
        selectSTR = "SELECT id, JSONB_BUILD_OBJECT( "
        selectSTR2 = ") AS JSONDOC FROM leads WHERE "
        for key, value in filters.iteritems():
            object_list = self.object_create(key, object_list)
            if fielddata[key] in "integer":
                data_type = "integer"
                param, querySTR, filter_clause = self.range_filter(key, value, param, querySTR, data_type,
                                                                   filter_clause)
            elif fielddata[key] in "currency float":
                data_type = "float"
                param, querySTR, filter_clause = self.range_filter(key, value, param, querySTR, data_type,
                                                                   filter_clause)
            elif fielddata[key] in "date datetime":
                data_type = "date"
                param, querySTR, filter_clause = self.range_filter(key, value, param, querySTR, data_type,
                                                                   filter_clause)
            elif fielddata[key] in "string email phone text url":
                if value == "":
                    pass
                else:
                    string_param = "%%" + value + "%%"
                    param.append(string_param)
                    paramSTR = "document->>'" + key + "' ILIKE %s"
                    querySTR.append(paramSTR)
                    filter_clause = 1
            elif fielddata[key] in "boolean":
                if value == "both":
                    pass
                elif value == "true":
                    paramSTR = "CAST(document->>'" + key + "' AS boolean) = TRUE "
                    querySTR.append(paramSTR)
                    filter_clause = 1
                elif value == "false":
                    paramSTR = "CAST(document->>'" + key + "' AS boolean) = FALSE "
                    querySTR.append(paramSTR)
                    filter_clause = 1
        sqlSTR = "AND ".join(querySTR)
        objectSTR = ",".join(object_list)
        cursor = connection.cursor()
        if filter_clause == 0:
            selectSTR2 = ") AS JSONDOC FROM leads "
            finalSTR = selectSTR + objectSTR + selectSTR2
            cursor.execute(finalSTR)
            csvdata = cursor.fetchall()

marketing_program_v2/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', 'client_id', 'client_secret', 'instance']

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"

marketing_program_v2/templates/base.html
{% load staticfiles i18n %}<!DOCTYPE html>
<html lang="en" ng-app>
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %}marketing_program_v2{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
  <script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

  {% block css %}
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/css/bootstrap.css">

  <!-- Your stuff: Third-party css libraries go here -->

  <!-- This file store project specific CSS -->
  <link href="{% static 'css/project.css' %}" rel="stylesheet">
  {% endblock %}

  {% block angular %}
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular.min.js"></script>
  {% endblock %}

</head>

<body>

<div class="m-b">
  <nav class="navbar navbar-dark navbar-static-top bg-inverse">
    <div class="container">
      <a class="navbar-brand" href="/">marketing_program_v2</a>
      <button type="button" class="navbar-toggler hidden-sm-up pull-xs-right" data-toggle="collapse"
              data-target="#bs-navbar-collapse-1">
        &#9776;
      </button>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-toggleable-xs" id="bs-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'about' %}">About</a>
          </li>
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'leads:home' %}">Leads</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'leads:view' %}">View</a>
          </li>
          {% endif %}
        </ul>

        <ul class="nav navbar-nav pull-xs-right">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Logout" %}</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
          </li>
          <li class="nav-item">
            <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Log In" %}</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
</div>

<div class="container">

  {% if messages %}
  {% for message in messages %}
  <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
  {% endfor %}
  {% endif %}

  {% block content %}
  <p>Use this document as a way to quick start any new project.</p>
  {% endblock content %}

</div> <!-- /container -->

<!--<div class="navbar navbar-default navbar-fixed-bottom" role="navigation">-->
<!--<div class="container">-->
<!--<p class="text-muted"><i>Copyright © DogPackApp.com</i></p>-->
<!--</div>-->
<!--</div>-->

{% block modal %}{% endblock modal %}

<!-- Le javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
{% block javascript %}
<!-- Latest JQuery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>

<!-- Tether - a requirement for Bootstrap tooltips -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js"></script>

<!-- Latest compiled and minified JavaScript -->
<script src="https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/js/bootstrap.js"></script>

<!-- Your stuff: Third-party javascript libraries go here -->

<!-- place project specific Javascript in this file -->
<script src="{% static 'js/leads.js' %}"></script>
<script src="{% static 'js/plugins.js' %}"></script>
{% endblock javascript %}
</body>
</html>